language: node_js
node_js:
  - "stable"
before_script:
  - npm install
stages:
  - lint
  - build
jobs:
  include:
  - stage: lint
    script: skip
  - stage: build
    script: npm run build
